name: Pipeline
on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master

jobs:
  testsuite:
    name: Testes Automatizados
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.0']

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, mysql, zlib, dom, openssl, soap, json, simplexml, libxml, mcrypt

      - name: checkout
        uses: actions/checkout@v2

      - name: criando-databases
        run: |
          cat app/Config/database.test.php > app/Config/database.php
          mysql -e "CREATE DATABASE cakephp_test"
          mysql -e "CREATE DATABASE cakephp_test2"
          mysql -e "CREATE DATABASE cakephp_test3"

      - name: Rodando PHPUnit
        run: |
          composer test
