name: Pipeline
on:
  push:
    branches:
      - master
      - develop

  pull_request:
    branches:
      - master

jobs:
  testsuite:
    name: Testes Automatizados
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.4', '8.0']
    steps:
      - uses: niden/actions-memcached@v7
      - uses: shogo82148/actions-setup-redis@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, intl, mysql, zlib, dom, openssl, soap, json, simplexml, libxml, mcrypt, sqlite3

      - name: checkout
        uses: actions/checkout@v2

      - name: criando-databases
        run: |
          mkdir app/tmp app/tmp/cache app/tmp/cache/models app/tmp/cache/persistent app/tmp/cache/views app/tmp/logs app/tmp/sessions app/tmp/tests
          mkdir lib/Cake/Test/test_app/tmp/cache lib/Cake/Test/test_app/tmp/cache/models lib/Cake/Test/test_app/tmp/cache/persistent lib/Cake/Test/test_app/tmp/cache/views lib/Cake/Test/test_app/tmp/logs lib/Cake/Test/test_app/tmp/sessions lib/Cake/Test/test_app/tmp/tests
          sudo locale-gen de_DE
          sudo locale-gen es_ES
          sudo systemctl start mysql.service
          mysql -uroot -p"root" -e "CREATE DATABASE cakephp_test"
          mysql -uroot -p"root" -e "CREATE DATABASE cakephp_test2"
          mysql -uroot -p"root" -e "CREATE DATABASE cakephp_test3"
          mysql -uroot -p"root" -e "SELECT version()"

      - name: Rodando PHPUnit
        run: |
          composer install --no-progress --no-suggest -o --no-ansi --no-interaction
          composer test
